version: "2"
services:
  cyanite-cassandra:
    hostname: cyanite-cassandra
    image: cassandra:3
  cyanite:
    hostname: cyanite
    build: .
    image: tehlers/docker-cyanite
    ports:
      - "8080:8080"
      - "8888:8888"
      - "2003:2003"
    environment:
      MAX_HEAP_SIZE: 512m
      CASSANDRA_HOST: cyanite-cassandra
    depends_on:
     - cyanite-cassandra
    links:
     - cyanite-cassandra
