version: "2"
services:
  cyanite:
    hostname: cyanite
    build: .
    image: greeninja/docker-cyanite
    ports:
      - "8080:8080"
      - "8888:8888"
      - "2003:2003"
    environment:
      MAX_HEAP_SIZE: 512m
      CASSANDRA_HOST: cyanite-cassandra
    depends_on:
     - cassandra
    links:
     - cassandra
   cassandra:
     hostname: cyanite-cassandra
     image: cassandra
